---

name: Check rbfeeder version

on:
  workflow_dispatch:
  pull_request:
    # Only publish on push to main branch
    branches:
      - main

jobs:

  version_in_container:
    name: Check version in 'latest' image
    runs-on: ubuntu-latest
    outputs:
      currver: ${{ steps.current-version.outputs.currver }}
    steps:
      - name: Get version from ghcr.io/sdr-enthusiasts/docker-radarbox:latest
        id: current-version
        run: |
          set -x
          echo "::set-output name=currver::$(docker run --rm --entrypoint cat ghcr.io/sdr-enthusiasts/docker-radarbox:latest /CONTAINER_VERSION)"

  latest_version:
    name: Check latest version of 'rbfeeder'
    runs-on: ubuntu-latest
    outputs:
      currver: ${{ steps.latest-version.outputs.latestver }}
    steps:
      - name: Build image
        uses: docker/build-push-action@v2
        with:
          push: false
          load: true
          tags: local-docker-radarbox:latest
      - name: Get version from newly built image
        id: latest-version
        run: |
          set -x
          echo "::set-output name=latestver::$(docker run --rm --entrypoint cat local-docker-radarbox:latest /CONTAINER_VERSION)"
